<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>bind</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cc82eb2d-6a40-4659-aa64-825740746976</testSuiteGuid>
   <testCaseLink>
      <guid>e5fa7258-0c0c-4192-820e-11332500e1f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1_Attribute</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b7aff660-fd15-480b-bda8-3d9f55c8c7ab</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data/excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>644eb283-2669-4720-970b-d911ab401201</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa47d6b8-d9a5-4924-93d1-0a844f1208a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b224a9b-aef7-491c-8b7a-9cc03bd713e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e0998fbc-9537-4ddf-aee0-fe7165d58393</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC2_CSS</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>05570bad-abbe-42ec-b6b1-c47e58ffca15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data/excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ff54274-4bb3-4d99-bfc3-d3e86387093f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35f85ee8-e18d-4b31-8775-9a8d03699172</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb32b54-5557-451e-9780-357ae76722fa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dd1e58c1-b036-43aa-96a9-17646e23f4c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC3_Image</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>685e91d4-540c-4397-8187-b031d2be627a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data/excel</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>600a2ebe-94ec-49ef-9d6d-e69352379602</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d41af34c-2eee-46e9-81d8-ab9ab0ce896d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4f3048e-dccb-4384-afed-db1a9c4c62d4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
